config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'artworks#index'
  resources :users, only: :show
  resources :artworks, only: [:index, :new, :create, :show] do
    collection do
      get 'all'
    end
    resources :bookings, only: [:new, :create, :index, :edit, :update]
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/artwork.rb
class Artwork < ApplicationRecord
  ARTSIZE = ['All sizes', 'small', 'medium', 'large']
  ARTTYPE = ['All types', 'Painting', 'Photography', 'Prints', 'Sculpture', 'Work on Paper', 'Design', 'Drawing', 'Installation', 'Film/Video']
  ARTCATEGORY = ['All Categories', 'Black & White', 'Graphik', 'Expressive', 'Colored']
  belongs_to :user
  has_many :bookings, dependent: :destroy

  validates :title, presence: true
  validates :size, presence: true
  validates :art_type, presence: true
  validates :category, presence: true
  validates :price, presence: true
  validates :address, presence: true
  validates :photo, presence: true

  mount_uploader :photo, PhotoUploader

  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :user
  belongs_to :artwork
  validates :status, inclusion: { in: ["Pending", "Accepted", "Declined"] }
end

app/models/user.rb
class User < ApplicationRecord
  has_many :artworks
  has_many :bookings
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  mount_uploader :photo, PhotoUploader
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :authenticate_user!
  include Pundit
  # after_action :verify_authorized, except: :index, unless: :skip_pundit?
  # after_action :verify_policy_scoped, only: :index, unless: :skip_pundit?
  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name, :username, :photo])

    # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: [:first_name, :last_name, :username, :description, :photo])
  end

  private

  def skip_pundit?
    devise_controller? || params[:controller] =~ /(^(rails_)?admin)|(^pages$)/
  end
end

app/controllers/artworks_controller.rb
class ArtworksController < ApplicationController
  skip_before_action :authenticate_user!, only: [:index, :show, :all]
  def index
    @artworks = ArtworkPolicy::Scope.new(current_user, Artwork).index
  end

  def new
    @artwork = Artwork.new
  end

  def all
    @artworks = policy_scope(Artwork).where.not(latitude: nil, longitude: nil)
    if !params[:art_type].nil? && !params[:art_type].empty? && params[:art_type] != "All types"
      @artworks = @artworks.where(art_type: params[:art_type])
    end

    if !params[:category].nil? && !params[:category].nil? && params[:category] != "All Categories"
      @artworks = @artworks.where(category: params[:category])
    end

    if !params[:size].nil? && !params[:size].nil? && params[:size] != "All sizes"
      @artworks = @artworks.where(size: params[:size])
    end

    @artworks = @artworks.near(params[:address], 10) if !params[:address].nil? && !params[:address].empty?

    @markers = @artworks.map do |artwork|
      {
        lat: artwork.latitude,
        lng: artwork.longitude,
        infoWindow: render_to_string(partial: "infowindow", locals: { artwork: artwork })
      }
    end
  end

  def create
    @artwork = Artwork.new(artwork_params)
    @artwork.user = current_user
    if @artwork.save!
      redirect_to artwork_path(@artwork)
    else
      render :new
    end
  end

  def show
    @artwork = Artwork.find(params[:id])
    @booking = Booking.new
  end

  private

  def artwork_params
    params.require(:artwork).permit(:title, :size, :art_type, :category, :price, :photo, :address, :latitude, :longitude)
  end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  def create
    @booking = Booking.new(booking_params)
    @artwork = Artwork.find(params[:artwork_id])
    @booking.artwork = @artwork
    @booking.user = current_user

    @booking.status = "Pending"

    if @booking.save!
      redirect_to user_path(current_user)
    else
      redirect_to artwork_path(@artwork)
    end
  end

  def index
    @booking_requests = Booking.select { |booking| booking.artwork.user == current_user }
    @bookings = Booking.where(user_id: current_user.id)
    # @artwork = current_user.artworks
  end

  def edit
    @booking = Booking.find(params[:id])
    @artwork = Artwork.find(params[:artwork_id])
  end

  def update
    @booking = Booking.find(params[:id])
    if @booking.update(booking_params)
      redirect_to artwork_path(@artwork)
    else
      render artwork_path(@artwork)
    end
  end

  def status_change
  end

  private

  def booking_params
    params.require(:booking).permit(:start_date, :end_date, :user_id, :artwork_id, :photo)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = current_user
    @bookings = Booking.where(user_id: current_user.id)
    @booking_requests = Booking.select { |booking| booking.artwork.user == current_user }
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/artworks/_infowindow.html.erb
<div class="map-img" style="position: relative">
  <%= cl_image_tag artwork.photo, :width => 200 %>
<div class="caption"><%= artwork.title %></div>
</div>
<br>
<center>
<div class="mapwindow-details">
  <h4>Artist: <strong><%= artwork.user.username %></strong></h4>
    <h4><strong><%= artwork.price %>€/day</h4></strong>
</div>
</center>
<br>
<div class="mapwindow-link">
  <%= link_to 'More details', artwork_path(artwork) %>
</div>

app/views/artworks/all.html.erb
<div class ="all-view">
  <%= form_tag(all_artworks_path, method: "get") do %>
        <%#= label_tag(:address, "Where") %>
        <%= text_field_tag(:address)%>
        <%= select_tag(:art_type, options_for_select(Artwork::ARTTYPE)) %>
        <%= select_tag(:size, options_for_select(Artwork::ARTSIZE)) %>
        <%= select_tag(:category, options_for_select(Artwork::ARTCATEGORY)) %>
        <%= submit_tag "Search", class: "card-btn-search"  %>
      <% end %>
</div>
<div class="map-content">
      <div class="map-cards">
  <% @artworks.each do |artwork| %>
  <%= link_to artwork_path(artwork) do%>
    <div class="card-result">
    <div class="inner-div" style="background: url(<%= cl_image_path artwork.photo %>) center">
    </div>
  </div>

    <div class="infos-card-ind">
      <h3 class="artwork-artist"><strong><%= artwork.title %></strong></h3>
      <h5><%= artwork.price %>€</h5>
      </div>
      <h4 class="artwork-title"><em><%= artwork.title %></em>, <%= artwork.art_date %></h4>
  <%end%>
  <%end%>

</div>


      <div
  id="map"
  style="width: 100%;
  height: 600px;"
  data-markers="<%= @markers.to_json %>"
  data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>"
></div>
</div>

app/views/artworks/index.html.erb
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.2),rgba(0,0,0,0.1)), url(https://2.bp.blogspot.com/-tXKI8DU4_QE/V_Kzh1Bx5jI/AAAAAAAAAoA/vCycQdtr4QASYbnqCoDw0zHi7T0tCh5tQCEw/s1600/w%25C5%2582a%25C5%259Bciwe.jpg);">
  <div class="form-home">
    <div class="container-home">
      <%= form_tag(all_artworks_path, method: "get") do %>
           <h1 id="big-title">Discover and rent artworks<br> by renowned and emerging artists.</h1>
            <div class ="animation-art">
           <h2 class="green-style">
           <left> <span id="typed"></span></left>
          </h2>
          </div>
        <%#= label_tag(:address, "Where") %>
        <div class ="search-bar-index">
        <%= text_field_tag(:address) %>
        <%= select_tag(:art_type, options_for_select(Artwork::ARTTYPE)) %>
        <%= submit_tag "Search", class: "card-btn-search" %>
        </div>
      <% end %>


<!--
      <form>
        <h1>Découvrez et louez des oeuvres <br> d’artistes confirmés et émergents.</h1>
        <div class="form-group">
          <label for="inputAddress">Où?</label>
          <input type="text" class="form-control" id="inputAddress" placeholder="City">
        </div>

        <div class="form-row">
            <div class="col">
            <label for="inputCity">Du</label>
            <input type="text" class="form-control" id="inputCity" placeholder="From">
            </div>

        <div class="col">
          <label for="inputDate">Au</label>
          <input type="text" class="form-control" id="inputDate" placeholder="To">
        </div>
        </div>

        <div class="form-group">
            <label for="inputType">Type</label>
            <input type="text" class="form-control" id="inputType" placeholder="Type?">
        </div>
        <button type="submit" class="btn btnsignlg">Rechercher</button>
      </form>
 -->


    </div>
  </div>
</div>
  <div class="bg-white">


<!-- <h1><center>All Artworks</center></h1> -->


<div class="container container-header">

  <div class="section-title">

<h1 id="section-title"><i class="fas fa-arrow-circle-down"></i> Latest artworks</h1>
  </div>

<div class="container-button">

<%= link_to "View all", all_artworks_path, class: "btnsignlg" %>
</div>

</div>

<div class="container bg-white">
<div class="container-ind">
  <% @artworks.each do |artwork| %>
  <%= link_to artwork_path(artwork) do%>
    <div class="card-result">
    <div class="inner-div" style="background: url(<%= cl_image_path artwork.photo %>) center">
    </div>
  </div>

    <div class="infos-card-ind">
      <h3 class="artwork-artist"><strong><%= artwork.user.username %></strong></h3>
      <h5><%= artwork.price %>€</h5>
      </div>
      <h4 class="artwork-title"><em><%= artwork.title %></em>, <%= artwork.art_date %></h4>
  <%end%>
  <%end%>
</div>
</div>
</div>

app/views/artworks/new.html.erb
<div class="add-artwork-img">
<div class="container-form">
  <div class="row justify-content-center">
      <div class="col-lg-10">
        <div class="form-model">
<h1><center>Add a new Artwork</center></h1>

<div class="banner">

  <div class="container-artwork">

<%= simple_form_for(@artwork) do |f| %>

  <div class="form-inputs">
    <%= f.input :title%>

    <%= f.input :size, collection: Artwork::ARTSIZE %>
    <%= f.input :art_type, collection: Artwork::ARTTYPE %>
    <%= f.input :category, collection: Artwork::ARTCATEGORY %>
    <%= f.input :price %>
    <%= f.input :address %>
    <%= f.input :photo %>
    <%= f.input :photo_cache, as: :hidden %>
  </div>

  <div class="form-actions">
    <%= f.button :submit, "Submit my artwork", class: "btnsign-inverse"  %>
  </div>
<% end %>
 </div>
</div>
</div>
</div>
</div>
</div>
</div>

app/views/artworks/show.html.erb
<div class="container">
  <%= link_to "View all artworks", all_artworks_path, class: "card-btn" %>
</div>

<div class="container">
  <div class= "card-container d-flex">

    <div class="show-artwork-image-card" id="card-left"
      style="background-image: url('<%= cl_image_path @artwork.photo, height: 300, width: 400, crop: :fill %>')">
    </div>

    <div class="show-artwork-description" id="card-right">
      <div class ="show-artwork-card">
        <h2><%= @artwork.category%></h2>
        <h1><strong><%= @artwork.title %></strong></h1>
        <span><strong><%= @artwork.price %>€/per day</strong></span>
        <p><strong><%="Size:  "%></strong><%= @artwork.size%></p>
        <p><strong><%="Date:  "%></strong><%= @artwork.art_date %></p>
        <p><strong><%="Type:  "%></strong><%= @artwork.art_type %></p>
        <p><strong><%="Technique:  "%></strong><%= @artwork.description %></p>

        <div class="">
          <div class="form-wrapper pr-4" style="width: 400px; margin: 0 auto;">
            <h2>Book your painting</h2>
            <%= simple_form_for([@artwork, @booking]) do |f| %>
              <%= f.input :start_date, as: :string, required: false, input_html: {class: "datepicker"} %>
              <%= f.input :end_date, as: :string, required: false, input_html: {class: "datepicker"} %>
              <%= f.submit "BOOK", class: "btn btn-primary" %>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/bookings/edit.html.erb
<h1><%= @booking.artwork.title %></h1>
<p><%= @booking.start_date %> - <%= @booking.end_date %></p>
<p><% simple_form_for [@artwork, @booking] do |f| %></p>
<p><%= f.input :status, :collection => ["Pending", "Accepted", "Declined"] %></p>
<button><% f.submit "Save" %></button>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>LocART | Louez vos oeuvres d'art</title>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= stylesheet_pack_tag 'application' %> <!-- NEW! -->
  </head>
  <body>
    <%= render "shared/navbar" %>
    <%= yield %>
    <%= javascript_include_tag 'application' %>
    <%= javascript_pack_tag 'application' %>
  </body>
  <%= render 'shared/footer' %>
</html>

app/views/shared/_footer.html.erb
<div class="footer">
  <div class="footer-links">
    <a href="#"><i class="fab fa-instagram"></i></a>
    <a href="#"><i class="fab fa-facebook"></i></a>
    <a href="#"><i class="fab fa-twitter"></i></a>
  </div>
  <div class="footer-copyright" style="font-size:10px; text-align: center">
        Legal Notice - Credits / © 2019 LE GANG -  All rights reserved.
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <%= link_to root_path, class: "navbar-brand" do %>
    <%= image_tag "https://i.ibb.co/Hdy78nT/LocArt.jpg" %>
  <% end %>


<!--
<div class=".search-form-control">
<%= simple_form_for :search, url: root_path, method: "GET", html: { class: 'form-inline' } do |f| %>
  <%= f.input :artwork, input_html: {placeholder: "Search"}, label: "" %>
  <%= f.submit "Search", class: "btn btnsignlg" %>
  <% end %>



</div>
 -->
  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto align-items-center">
      <li class="nav-item">

          <% if user_signed_in? %>
          <%= link_to "Add an Artwork", new_artwork_path, class: "btnsignsm" %>
          <%end %>

       <% if user_signed_in? %>
          Welcome back <strong><%= current_user.first_name %></strong> !!
<!--          link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'
 -->       <% else %>
        <div class="nav-button">
          <div class="container-button">
         <%= link_to "Sign up", new_user_registration_path, class: "btnsignlg-inverse"  %>
         <%= link_to "Login", new_user_session_path, class: "btnsignlg"  %>
        </div>
      <% end %>

      </li>
      <li class="nav-item dropdown">
        <% if user_signed_in? %>
        <% if current_user.photo.blank? %>
        <%= image_tag "https://storage.gra3.cloud.ovh.net/v1/AUTH_ca60d77ddd5e42749d7c4c17f753540d/ugm-data/pictures/larabesque/896133-pochoir-de-batman-sigle-de-batman-logo-de-batman-ref-415-2-1_medium.webp?1551742798", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
        <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
          <%= link_to "Artworks", all_artworks_path, class: "dropdown-item" %>
          <%= link_to "My Profile", edit_user_registration_path, class: "dropdown-item" %>
          <%= link_to "My bookings", user_path(current_user), class: "dropdown-item" %>
          <%= link_to "Log out", destroy_user_session_path, class: "dropdown-item", method: "delete" %>
          <% else %>
        <%= cl_image_tag current_user.photo, class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <%= link_to "Artworks", all_artworks_path, class: "dropdown-item" %>
            <%= link_to "My Profile", edit_user_registration_path, class: "dropdown-item" %>
            <%= link_to "My bookings", all_artworks_path, class: "dropdown-item" %>
            <%= link_to "Log out", destroy_user_session_path, class: "dropdown-item", method: "delete" %>
          <% end %>
            <% else %>
            <%#= link_to "Home", artworks_path, class: "dropdown-item" %>
          <% end %>
        </div>
      </li>
    </ul>
  </div>
</div>

app/views/users/show.html.erb
<div class="login-img-new" id="mybookings">
  <div class="custom-container">
    <div class="custom-button-two">
      <button class="btnsign-inverse" type="button" data-toggle="collapse" data-target="#collapseExample" aria-expanded="false" aria-controls="collapseExample">
      My bookings
      </button>
        <button class="btnsign-inverse" type="button" data-toggle="collapse" data-target="#collapseBooking" aria-expanded="false" aria-controls="collapseExample">
        My booked artworks
        </button>
    </div>
    <div>
      <div class="main-booking-first collapse show" id="collapseExample">
        <h2>My bookings<br></h2>
          <% @bookings.each do |booking| %>
          <div class="item-booking">
            <div class="img-booking">
              <%= cl_image_tag(booking.artwork.photo, width: 400, height: 300, crop: :fill
)%>
            </div>
            <div class ="content-booking">
              <p><span style="color:#144C52"><strong><%= "Artist name: " %></strong><%= booking.artwork.user.username%></span></p>
              <h3 class="artwork-artist"><span style="color:#144C52"><%= "Title: " %></span><strong><%= booking.artwork.title %></strong></h3>

              <h4 class="artwork-title"><span style="color:#144C52"><strong><%= "Price: " %></strong><%= booking.artwork.price %>€/day</span></h4>
              <h4 class="artwork-title"><span style="color:#144C52"><strong><%= "Type: " %></strong><%= booking.artwork.art_type %></span></h4>
              <div class="date-status">
                    <p class="date">
                      <i class="far fa-calendar"></i>
                      <span class=""><strong><%= booking.start_date %> to <%= booking.end_date %></strong></span>
                    </p>
                    <% if booking.artwork.user != current_user && booking.status == 'Pending' %>
                    <p><span style="color:#144C52"><strong>Status: </strong></span><strong>Awaiting confirmation...</strong></p>
                    <% elsif %>
                    <% booking.artwork.user != current_user && booking.status == 'Approved' %>
                    <i class="far fa-check-circle"></i> <strong><%= "Your request has been approved" %></strong>
                    <% else %>
                    <% booking.artwork.user != current_user && booking.status == 'Declined' %>
                    <i class="fas fa-ban"></i> <strong><%= "Sorry, the artwork is unavailable" %></strong>
                  <% end %>
              </div>
            </div>
          </div>
        <% end %>
      </div>
<div class="container">
      <div class="wrapper">

        <div class="main-booking collapse" id="collapseBooking">
          <h2>My artworks <br></h2>
            <% @booking_requests.each do |booking| %>
            <div class="item-booking">
              <div class="img-booking">
                <%= cl_image_tag booking.artwork.photo%>
              </div>
              <div class ="content-booking">
                <p><span style="color:#144C52"><strong><%= "Artist name: " %></strong>Requested by: <%= booking.user.username %></span></p>
                <h3 class="artwork-artist"><span style="color:#144C52"><%= "Title: " %></span><strong><%= booking.artwork.title %></strong></h3>

                <h4 class="artwork-title"><span style="color:#144C52"><strong><%= "Price: " %></strong><%= booking.artwork.price %>€/day</span></h4>
                <h4 class="artwork-title"><span style="color:#144C52"><strong><%= "Type: " %></strong><%= booking.artwork.art_type %></span></h4>
                <div class="date-status">
                      <p class="date">
                        <i class="far fa-calendar"></i>
                        <span class=""><strong><%= booking.start_date %> to <%= booking.end_date %></strong></span>
                      </p>
                      <% if booking.artwork.user == current_user && booking.status == 'Pending' %>
            <button type="button" class="btn btn-danger">cancel</button>

        <% elsif %>
          <% booking.artwork.user == curent_user && booking.status == 'Accepted' %>
            <i class="far fa-check-circle"></i>
          </p>
        <% else %>
           <% booking.artwork.user == curent_user && booking.status == 'Declined' %>
            <i class="fas fa-ban"></i>
          </p>
        <% end %>
        </div>
                </div>
              </div>
            </div>
          <% end %>
        </div>
    </div>
  </div>
    </div>
    </div>
</div>
</div>